sudo: required
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  # Generate service account in Google Cloud
  # Then download, isntall travis CI and login
  # Encrypt and upload the JSON to travis CI
  - gcloud config set project # Here goes the project ID
  - gcloud config set compute/zone # Zone where the app is
  - gcloud container clusters get-credentials # Name of the cluster
  # Docker part -------------------
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin