sudo: required
services:
  - docker

before_install:
  - docker build -t darking360/docker-complex-client:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run darking360/docker-complex-client:latest npm run test -- --coverage

after_success:
  - docker build -t darking360/docker-complex-client:latest ./client
  - docker build -t darking360/docker-complex-server:latest ./server
  - docker build -t darking360/docker-complex-worker:latest ./worker
  - docker build -t darking360/docker-complex-nginx:latest ./nginx

  # Login into docker HUB with docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push darking360/docker-complex-client:latest
  - docker push darking360/docker-complex-server:latest
  - docker push darking360/docker-complex-worker:latest
  - docker push darking360/docker-complex-nginx:latest

